kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: database
spec:
  capacity:
    storage: 10Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /data/postgres-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube