kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  namespace: database
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 31000
  
