apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: cicd
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent-service
  namespace: cicd
spec:
  selector:
    app: jenkins-agent
  type: ClusterIP
  ports:
    - port: 4444
      targetPort: 22
