apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: cicd
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  serviceName: jenkins-service
  template:
    metadata:
      labels:
        app: jenkins
      namespace: cicd
    spec:
      # securityContext:
      #   fsGroup: 1000
      #   runAsUser: 1000
      # serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins-controller:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "3Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_home/casc_configs/jenkins.yaml
            - name: HOST_IP
              value: $(jenkins-service)
            - name: AGENT_IP
              value: jenkins-agent-service
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /media/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc